### PR TITLE
Closes #14 Base /me endpoints and tests

### LINKED ISSUE #14: /me base implementation
Support the `/me` endpoint. It should support Retrieval, Signup/Create, Update and Delete.

### PR DESCRIPTION
**Pull request by nikola-mladenovic**
@cneijenhuis @lauraluiz - Base /me endpoints and tests

### CODE REVIEW

**Comment by lauraluiz** [comment]
👍

**Comment by cneijenhuis** [comment]
Code itself LGTM. Some thoughts on the naming of the Endpoint classes (should have probably brought this up for `Cart` already):
* `Cart` and `Customer` are probably also the names we want to give our model classes. :question: 
* We should try to not have them clash with the names for the regular endpoints (e.g. `/me` vs `/customers`). (For customers, there is a small use case to retrieve them: Reviews may reference other customers)
* Should we go with singular or plural? (`/me` is really singular, but `/me/carts` can return multiple carts...)

Maybe `MyCarts`, `MyProfile`, `Products`, `Categories`, `Customers`, ... would work. Thanks to plural, the names will not clash with the model classes. However, the difference is quite subtle.

`MyCartsEndpoint`, `ProductsEndpoint`, `CustomersEndpoint` etc. would work as well, but doesn't look as nice.

What do you think? @nikola-mladenovic @lauraluiz

**Comment by nikola-mladenovic** [comment]
My thoughts are going in direction of active record pattern. That being said, I think the our actual endpoints and models should have the same name (but do a clean separation in code with extension).

That would result in i.e `Cart` being our model + having static methods for accessing data from the endpoints. As a result, you will be able to have code like:

```swift
Cart.byId("some-id", result: { result in
    let myCart: Cart = result.response
    // Do something with myCart, e.g myCart.lineItems?.forEach...
})

// Or if we also implement synchronous methods
let myCart: Cart = Cart.byId("some-id", wait: true)
// ...
let someCarts: [Cart] = Cart.query(limit: 10, wait: true)
// Do something with someCarts, e.g someCarts.first?.lineItems?.forEach...
```

**Comment by cneijenhuis** [comment]
I haven't thought about extensions - good point, they can help us.

Can you sketch how would it work with `/me` and `/customers`? They should be two different endpoint-classes (IMO?), but should share the same model.

**Comment by nikola-mladenovic** [comment]
For those rare cases where multiple endpoints have the same response models, we conform our different endpoint classes to one common protocol, and that common protocol has a default extension containing properties which model the response.

**Comment by cneijenhuis** [comment]
OK. So you'd like to keep `Cart` and `Customer` for now or go with `MyCart` and `MyProfile`?

I guess I'm fine with both. `My...` may make it easier to find the correct documentation, on the other hand `Cart` and `Customer` may be more intuitive because in most cases, one would not access the regular endpoint with the iOS SDK.

**Comment by cneijenhuis** [comment]
Anyway, LGTM either way :wink: :+1:

**Pull request merged**
